version: '2'

services:
    jupyter:
        container_name: jupyter_notebook
        image: tuzkimo/jupyter_notebook
        ports:
            - 8765:8888
        volumes:
            - ./work:/home/jovyan/work
        command: >
            start-notebook.sh
            --NotebookApp.password='sha1:772f104e6c00:fa76619ae32f722866120bb59f64d2b8702385b2'
        restart: always